export const ACTIONS = {
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',

  IN_PROGRESS: 'IN_PROGRESS',
  SUCCESS: 'SUCCESS',

  CREATE_GAME: 'CREATE_GAME',
  GAME_CREATED: 'GAME_CREATED',
  FETCH_GAME: 'FETCH_GAME',
  GAME_UPDATED: 'GAME_UPDATED',

  CREATE_PLAYER: 'CREATE_PLAYER'
};
